In [2]:
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Multiply

import numpy as np

In [3]:
input_1 = Input(shape=(2,3))
mask_1 = Input(shape=(2,1))

In [4]:
net = Multiply()([input_1, mask_1])
net = Model(inputs=[input_1, mask_1], outputs=net)

In [5]:
print(net.summary())

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 2, 3)]       0                                            
__________________________________________________________________________________________________
input_2 (InputLayer)            [(None, 2, 1)]       0                                            
__________________________________________________________________________________________________
multiply (Multiply)             (None, 2, 3)         0           input_1[0][0]                    
                                                                 input_2[0][0]                    
Total params: 0
Trainable params: 0
Non-trainable params: 0
__________________________________________________________________________________________________
None


In [10]:
arr1 = np.array([1,2,3,4,4,4]).reshape((1,2,3))
arr2 = np.array([1,0]).reshape((1,2,1))

In [11]:
print(net.predict([arr1, arr2]))

[[[1. 2. 3.]
  [0. 0. 0.]]]


A more complex example, at a certain point in the double_unet we have:
```
sigmoid60           |  (256)               =>   (256)               0           #!!!!!   
mult_10             |  (256, 32, 32)       =>   (256, 32, 32)       0           #!!!!!  
```

In [31]:
input_1 = Input(shape=(256,1,1))
mask_1 = Input(shape=(256,32,32))

In [32]:
net = Multiply()([input_1, mask_1])
net = Model(inputs=[input_1, mask_1], outputs=net)

In [33]:
print(net.summary())

Model: "model_2"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_7 (InputLayer)            [(None, 256, 1, 1)]  0                                            
__________________________________________________________________________________________________
input_8 (InputLayer)            [(None, 256, 32, 32) 0                                            
__________________________________________________________________________________________________
multiply_3 (Multiply)           (None, 256, 32, 32)  0           input_7[0][0]                    
                                                                 input_8[0][0]                    
Total params: 0
Trainable params: 0
Non-trainable params: 0
__________________________________________________________________________________________________
None


In [38]:
arr1 = np.array([range(256)]).reshape((1,256,1,1))
arr2 = np.ones(256*32*32).reshape((1,256,32,32))

In [37]:
print(net.predict([arr1, arr2]))

[[[[  0.   0.   0. ...   0.   0.   0.]
   [  0.   0.   0. ...   0.   0.   0.]
   [  0.   0.   0. ...   0.   0.   0.]
   ...
   [  0.   0.   0. ...   0.   0.   0.]
   [  0.   0.   0. ...   0.   0.   0.]
   [  0.   0.   0. ...   0.   0.   0.]]

  [[  1.   1.   1. ...   1.   1.   1.]
   [  1.   1.   1. ...   1.   1.   1.]
   [  1.   1.   1. ...   1.   1.   1.]
   ...
   [  1.   1.   1. ...   1.   1.   1.]
   [  1.   1.   1. ...   1.   1.   1.]
   [  1.   1.   1. ...   1.   1.   1.]]

  [[  2.   2.   2. ...   2.   2.   2.]
   [  2.   2.   2. ...   2.   2.   2.]
   [  2.   2.   2. ...   2.   2.   2.]
   ...
   [  2.   2.   2. ...   2.   2.   2.]
   [  2.   2.   2. ...   2.   2.   2.]
   [  2.   2.   2. ...   2.   2.   2.]]

  ...

  [[253. 253. 253. ... 253. 253. 253.]
   [253. 253. 253. ... 253. 253. 253.]
   [253. 253. 253. ... 253. 253. 253.]
   ...
   [253. 253. 253. ... 253. 253. 253.]
   [253. 253. 253. ... 253. 253. 253.]
   [253. 253. 253. ... 253. 253. 253.]]

  [[254. 254. 254. ..